services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pedidosapp-sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Coti@2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data: